# MySQL.  Versions 4.1 and 5.0 are recommended.
base: &base
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  strict: false
  reconnect: false
  wait_timeout: 600
  pool: 25
  strict: false
  host: localhost
  port: 3306
  # 部署环境需要修改此账号密码
  username: root
  password:  '123abc..'

development:
  <<: *base
  database: office_manage_dev

test:
  <<: *base
  database: office_manage_test

staging:
  <<: *base
  database: office_manage_staging

production:
  <<: *base
  database: office_manage
